services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-service
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - tigo_gestion_solicitudes_n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  tigo_gestion_solicitudes_n8n_data:
    external: true
